version: '3.1'

networks:
  hotel-network:
    driver: bridge

services:
  hotel-search:
    build:
      context: ./hotel-search
      dockerfile: ./Dockerfile
    image: hotel-search
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotels_database
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    ports:
      - 8080:8080
    networks:
        - hotel-network

  hotel-availability:
    build:
      context: ./hotel-availability
      dockerfile: ./Dockerfile
    image: hotel-availability
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotels_database
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
        - hotel-network

  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    networks:
        - hotel-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotels_database 

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
        - hotel-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - hotel-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
      KAFKA_CREATE_TOPICS: 'hotel_availability_searches:1:3:compact'